/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package money.manager;

import java.awt.*;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author mahdi
 */
public class Daily extends javax.swing.JFrame {

    /**
     * Creates new form Daily
     */
    public Daily() {
        initComponents();
        showPieChart();
    }
    
    /**
     *
     */
    public final void showPieChart(){
        
        //create dataset
      DefaultPieDataset barDataset = new DefaultPieDataset( );
      barDataset.setValue( "Food" , new Double (2000) );  
      barDataset.setValue( "Entertainment" , new Double (2725) );   
      barDataset.setValue( "Shopping" , new Double (5468) );
      
      //create chart
       JFreeChart piechart = ChartFactory.createPieChart("mobile sales",barDataset, false,true,false);//explain
      
        PiePlot piePlot =(PiePlot) piechart.getPlot();
      
       //changing pie chart blocks colors
       piePlot.setSectionPaint("Food", new Color(0,204,102));
        piePlot.setSectionPaint("Entertainment", new Color(255,153,51));
        piePlot.setSectionPaint("Shopping", new Color(255,255,0));
      
       
        piePlot.setBackgroundPaint(new Color(153,153,255));
        
        //create chartPanel to display chart(graph)
        ChartPanel barChartPanel = new ChartPanel(piechart);
        panelBarChart.removeAll();
        panelBarChart.add(barChartPanel, BorderLayout.CENTER);
        panelBarChart.validate();
    }
    
    Toolkit tk = Toolkit.getDefaultToolkit();
    int screenWidth = (int)tk.getScreenSize().getWidth();
    int screenHeight = (int)tk.getScreenSize().getHeight();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new java.awt.Panel();
        panel1 = new java.awt.Panel();
        panel3 = new java.awt.Panel();
        label1 = new java.awt.Label();
        jTextField1 = new javax.swing.JTextField();
        panel4 = new java.awt.Panel();
        label2 = new java.awt.Label();
        jTextField2 = new javax.swing.JTextField();
        panel5 = new java.awt.Panel();
        panel13 = new java.awt.Panel();
        label3 = new java.awt.Label();
        panel9 = new java.awt.Panel();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        panel12 = new java.awt.Panel();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        panel10 = new java.awt.Panel();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        panel2 = new java.awt.Panel();
        panel6 = new java.awt.Panel();
        panel8 = new java.awt.Panel();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();
        label13 = new java.awt.Label();
        label14 = new java.awt.Label();
        label15 = new java.awt.Label();
        label16 = new java.awt.Label();
        panelBarChart = new java.awt.Panel();
        panel7 = new java.awt.Panel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds((screenWidth/2)-400, (screenHeight/2)-250, 0, 0);

        Header.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1272, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        panel1.setPreferredSize(new java.awt.Dimension(300, 400));
        panel1.setLayout(new java.awt.BorderLayout());

        panel3.setPreferredSize(new java.awt.Dimension(300, 25));
        panel3.setLayout(new javax.swing.BoxLayout(panel3, javax.swing.BoxLayout.LINE_AXIS));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(204, 204, 204));
        label1.setPreferredSize(new java.awt.Dimension(50, 25));
        label1.setText("Date");
        panel3.add(label1);

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setPreferredSize(new java.awt.Dimension(71, 25));
        panel3.add(jTextField1);

        panel1.add(panel3, java.awt.BorderLayout.NORTH);

        panel4.setBackground(new java.awt.Color(255, 102, 102));
        panel4.setPreferredSize(new java.awt.Dimension(300, 75));

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setBackground(new java.awt.Color(255, 102, 102));
        label2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        label2.setPreferredSize(new java.awt.Dimension(250, 50));
        label2.setText("Total Money Spent");
        panel4.add(label2);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 102, 102));
        jTextField2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        jTextField2.setText("8,393/-");
        jTextField2.setBorder(null);
        panel4.add(jTextField2);

        panel1.add(panel4, java.awt.BorderLayout.CENTER);

        panel5.setBackground(new java.awt.Color(102, 102, 255));
        panel5.setPreferredSize(new java.awt.Dimension(300, 250));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 20);
        flowLayout1.setAlignOnBaseline(true);
        panel5.setLayout(flowLayout1);

        panel13.setBackground(new java.awt.Color(102, 102, 255));
        panel13.setPreferredSize(new java.awt.Dimension(260, 25));

        label3.setBackground(new java.awt.Color(102, 102, 255));
        label3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        label3.setPreferredSize(new java.awt.Dimension(240, 20));
        label3.setText("Each Categories");

        javax.swing.GroupLayout panel13Layout = new javax.swing.GroupLayout(panel13);
        panel13.setLayout(panel13Layout);
        panel13Layout.setHorizontalGroup(
            panel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel13Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel13Layout.setVerticalGroup(
            panel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panel5.add(panel13);

        panel9.setBackground(new java.awt.Color(0, 204, 102));
        panel9.setPreferredSize(new java.awt.Dimension(120, 40));
        java.awt.FlowLayout flowLayout3 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0);
        flowLayout3.setAlignOnBaseline(true);
        panel9.setLayout(flowLayout3);

        label4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        label4.setPreferredSize(new java.awt.Dimension(100, 20));
        label4.setText("Food");
        panel9.add(label4);

        label5.setAlignment(java.awt.Label.RIGHT);
        label5.setMinimumSize(new java.awt.Dimension(120, 20));
        label5.setPreferredSize(new java.awt.Dimension(100, 20));
        label5.setText("2000");
        panel9.add(label5);

        panel5.add(panel9);

        panel12.setBackground(new java.awt.Color(255, 153, 51));
        panel12.setPreferredSize(new java.awt.Dimension(120, 40));
        java.awt.FlowLayout flowLayout4 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0);
        flowLayout4.setAlignOnBaseline(true);
        panel12.setLayout(flowLayout4);

        label6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        label6.setPreferredSize(new java.awt.Dimension(100, 20));
        label6.setText("Entertainment");
        panel12.add(label6);

        label7.setAlignment(java.awt.Label.RIGHT);
        label7.setMinimumSize(new java.awt.Dimension(120, 20));
        label7.setPreferredSize(new java.awt.Dimension(100, 20));
        label7.setText("2,725");
        panel12.add(label7);

        panel5.add(panel12);

        panel10.setBackground(new java.awt.Color(255, 255, 0));
        panel10.setPreferredSize(new java.awt.Dimension(120, 40));
        java.awt.FlowLayout flowLayout5 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0);
        flowLayout5.setAlignOnBaseline(true);
        panel10.setLayout(flowLayout5);

        label8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        label8.setPreferredSize(new java.awt.Dimension(100, 20));
        label8.setText("Shopping");
        panel10.add(label8);

        label9.setAlignment(java.awt.Label.RIGHT);
        label9.setMinimumSize(new java.awt.Dimension(120, 20));
        label9.setPreferredSize(new java.awt.Dimension(100, 20));
        label9.setText("5,468");
        panel10.add(label9);

        panel5.add(panel10);

        panel1.add(panel5, java.awt.BorderLayout.SOUTH);

        getContentPane().add(panel1, java.awt.BorderLayout.LINE_START);

        panel2.setLayout(new java.awt.BorderLayout());

        panel6.setPreferredSize(new java.awt.Dimension(600, 150));
        panel6.setLayout(new java.awt.BorderLayout());

        panel8.setBackground(new java.awt.Color(153, 153, 255));
        panel8.setPreferredSize(new java.awt.Dimension(200, 150));
        java.awt.FlowLayout flowLayout6 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 2);
        flowLayout6.setAlignOnBaseline(true);
        panel8.setLayout(flowLayout6);

        label10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        label10.setPreferredSize(new java.awt.Dimension(175, 40));
        label10.setText("Category Analyser");
        panel8.add(label10);

        label11.setBackground(new java.awt.Color(0, 204, 102));
        label11.setPreferredSize(new java.awt.Dimension(45, 10));
        panel8.add(label11);

        label12.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        label12.setPreferredSize(new java.awt.Dimension(100, 12));
        label12.setText("Food");
        panel8.add(label12);

        label13.setBackground(new java.awt.Color(255, 153, 51));
        label13.setPreferredSize(new java.awt.Dimension(45, 10));
        panel8.add(label13);

        label14.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        label14.setPreferredSize(new java.awt.Dimension(100, 12));
        label14.setText("Entertainment");
        panel8.add(label14);

        label15.setBackground(new java.awt.Color(255, 255, 0));
        label15.setPreferredSize(new java.awt.Dimension(45, 10));
        panel8.add(label15);

        label16.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        label16.setPreferredSize(new java.awt.Dimension(100, 12));
        label16.setText("Shopping");
        panel8.add(label16);

        panel6.add(panel8, java.awt.BorderLayout.WEST);

        panelBarChart.setBackground(new java.awt.Color(153, 153, 255));
        panelBarChart.setLayout(new java.awt.BorderLayout());
        panel6.add(panelBarChart, java.awt.BorderLayout.CENTER);

        panel2.add(panel6, java.awt.BorderLayout.CENTER);

        panel7.setPreferredSize(new java.awt.Dimension(600, 250));
        panel7.setLayout(new javax.swing.BoxLayout(panel7, javax.swing.BoxLayout.LINE_AXIS));
        panel2.add(panel7, java.awt.BorderLayout.SOUTH);

        getContentPane().add(panel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Daily.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Daily.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Daily.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Daily.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Daily().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel Header;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.Panel panel1;
    private java.awt.Panel panel10;
    private java.awt.Panel panel12;
    private java.awt.Panel panel13;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.Panel panel4;
    private java.awt.Panel panel5;
    private java.awt.Panel panel6;
    private java.awt.Panel panel7;
    private java.awt.Panel panel8;
    private java.awt.Panel panel9;
    private java.awt.Panel panelBarChart;
    // End of variables declaration//GEN-END:variables
}
