/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package money.manager;

import java.awt.*;

/**
 *
 * @author mahdi
 */
public class Filter extends javax.swing.JFrame {

    /**
     * Creates new form Filter
     */
    public Filter() {
        initComponents();
    }

    Toolkit tk = Toolkit.getDefaultToolkit();
    int screenWidth = (int)tk.getScreenSize().getWidth();
    int screenHeight = (int)tk.getScreenSize().getHeight();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        panel3 = new java.awt.Panel();
        panel7 = new java.awt.Panel();
        panel2 = new java.awt.Panel();
        label1 = new java.awt.Label();
        jTextField1 = new javax.swing.JTextField();
        panel4 = new java.awt.Panel();
        label2 = new java.awt.Label();
        jTextField2 = new javax.swing.JTextField();
        panel5 = new java.awt.Panel();
        label3 = new java.awt.Label();
        jTextField3 = new javax.swing.JTextField();
        panel6 = new java.awt.Panel();
        label4 = new java.awt.Label();
        jTextField4 = new javax.swing.JTextField();
        panel8 = new java.awt.Panel();
        label5 = new java.awt.Label();
        jComboBox1 = new javax.swing.JComboBox<>();
        panel9 = new java.awt.Panel();
        label6 = new java.awt.Label();
        jTextField5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds((screenWidth/2)-400, (screenHeight/2)-250, 0, 0);
        setResizable(false);

        panel1.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(panel1, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(panel3, java.awt.BorderLayout.CENTER);

        panel7.setBackground(new java.awt.Color(102, 102, 102));
        panel7.setMinimumSize(new java.awt.Dimension(250, 100));
        panel7.setPreferredSize(new java.awt.Dimension(250, 400));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10);
        flowLayout1.setAlignOnBaseline(true);
        panel7.setLayout(flowLayout1);

        panel2.setBackground(new java.awt.Color(102, 102, 102));
        panel2.setForeground(new java.awt.Color(102, 102, 102));
        panel2.setPreferredSize(new java.awt.Dimension(110, 50));

        label1.setForeground(new java.awt.Color(204, 204, 204));
        label1.setPreferredSize(new java.awt.Dimension(100, 15));
        label1.setText("From Date");

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setBorder(null);
        jTextField1.setPreferredSize(new java.awt.Dimension(100, 20));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        panel2.add(jTextField1);

        panel7.add(panel2);

        panel4.setBackground(new java.awt.Color(102, 102, 102));
        panel4.setForeground(new java.awt.Color(102, 102, 102));
        panel4.setPreferredSize(new java.awt.Dimension(110, 50));

        label2.setForeground(new java.awt.Color(204, 204, 204));
        label2.setPreferredSize(new java.awt.Dimension(100, 15));
        label2.setText("To Date");
        panel4.add(label2);

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        jTextField2.setPreferredSize(new java.awt.Dimension(100, 20));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        panel4.add(jTextField2);

        panel7.add(panel4);

        panel5.setBackground(new java.awt.Color(102, 102, 102));
        panel5.setForeground(new java.awt.Color(102, 102, 102));
        panel5.setPreferredSize(new java.awt.Dimension(110, 50));

        label3.setForeground(new java.awt.Color(204, 204, 204));
        label3.setPreferredSize(new java.awt.Dimension(100, 15));
        label3.setText("From Expense");
        panel5.add(label3);

        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setForeground(new java.awt.Color(0, 0, 0));
        jTextField3.setPreferredSize(new java.awt.Dimension(100, 20));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        panel5.add(jTextField3);

        panel7.add(panel5);

        panel6.setBackground(new java.awt.Color(102, 102, 102));
        panel6.setForeground(new java.awt.Color(102, 102, 102));
        panel6.setPreferredSize(new java.awt.Dimension(110, 50));

        label4.setForeground(new java.awt.Color(204, 204, 204));
        label4.setPreferredSize(new java.awt.Dimension(100, 15));
        label4.setText("To Expense");
        panel6.add(label4);

        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jTextField4.setForeground(new java.awt.Color(0, 0, 0));
        jTextField4.setPreferredSize(new java.awt.Dimension(100, 20));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        panel6.add(jTextField4);

        panel7.add(panel6);

        panel8.setBackground(new java.awt.Color(102, 102, 102));
        panel8.setForeground(new java.awt.Color(102, 102, 102));
        panel8.setPreferredSize(new java.awt.Dimension(230, 50));

        label5.setForeground(new java.awt.Color(204, 204, 204));
        label5.setPreferredSize(new java.awt.Dimension(215, 15));
        label5.setText("Category");
        panel8.add(label5);

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Food", "Entertainment", "Shopping" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(215, 20));
        panel8.add(jComboBox1);

        panel7.add(panel8);

        panel9.setBackground(new java.awt.Color(153, 153, 153));
        panel9.setPreferredSize(new java.awt.Dimension(230, 100));

        label6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        label6.setPreferredSize(new java.awt.Dimension(215, 30));
        label6.setText("Total");
        panel9.add(label6);

        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setForeground(new java.awt.Color(0, 0, 0));
        jTextField5.setPreferredSize(new java.awt.Dimension(215, 40));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        panel9.add(jTextField5);

        panel7.add(panel9);

        getContentPane().add(panel7, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Filter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Filter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Filter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Filter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Filter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.Panel panel4;
    private java.awt.Panel panel5;
    private java.awt.Panel panel6;
    private java.awt.Panel panel7;
    private java.awt.Panel panel8;
    private java.awt.Panel panel9;
    // End of variables declaration//GEN-END:variables
}
