/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package money.manager;

import java.awt.*;

/**
 *
 * @author MdMahdiMohtasim
 */
public class Settings extends javax.swing.JFrame {

    /**
     * Creates new form Settings
     */
    public Settings() {
        initComponents();
    }
    
    Toolkit tk = Toolkit.getDefaultToolkit();
    int screenWidth = (int)tk.getScreenSize().getWidth();
    int screenHeight = (int)tk.getScreenSize().getHeight();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rSButtonHover4 = new rojerusan.RSButtonHover();
        rSButtonHover5 = new rojerusan.RSButtonHover();
        rSButtonHover6 = new rojerusan.RSButtonHover();
        rSButtonHover7 = new rojerusan.RSButtonHover();
        rSButtonHover8 = new rojerusan.RSButtonHover();
        rSButtonHover9 = new rojerusan.RSButtonHover();
        rSButtonHover10 = new rojerusan.RSButtonHover();
        rSButtonHover11 = new rojerusan.RSButtonHover();
        rSButtonHover12 = new rojerusan.RSButtonHover();
        rSButtonHover13 = new rojerusan.RSButtonHover();
        jButton10 = new javax.swing.JButton();
        Body = new java.awt.Panel();
        Profile = new java.awt.Panel();
        Picture = new java.awt.Panel();
        Mahdi_Pic = new javax.swing.JLabel();
        User_Info = new java.awt.Panel();
        Welcome = new java.awt.Label();
        Info = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        User_Settings = new java.awt.Panel();
        panel2 = new java.awt.Panel();
        label2 = new java.awt.Label();
        panel1 = new java.awt.Panel();
        panel4 = new java.awt.Panel();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label7 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        panel6 = new java.awt.Panel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Settings");
        setBounds((screenWidth/2)-400, (screenHeight/2)-250, 0, 0);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(784, 450));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(784, 62));

        rSButtonHover4.setBackground(new java.awt.Color(153, 51, 0));
        rSButtonHover4.setText("Monthly");
        rSButtonHover4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        rSButtonHover4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover4ActionPerformed(evt);
            }
        });

        rSButtonHover5.setBackground(new java.awt.Color(153, 51, 0));
        rSButtonHover5.setText("Filter");
        rSButtonHover5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        rSButtonHover5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover5ActionPerformed(evt);
            }
        });

        rSButtonHover6.setBackground(new java.awt.Color(153, 51, 0));
        rSButtonHover6.setText("Stats");
        rSButtonHover6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        rSButtonHover6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover6ActionPerformed(evt);
            }
        });

        rSButtonHover7.setBackground(new java.awt.Color(153, 51, 0));
        rSButtonHover7.setText("Daily");
        rSButtonHover7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        rSButtonHover7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover7ActionPerformed(evt);
            }
        });

        rSButtonHover8.setBackground(new java.awt.Color(153, 51, 0));
        rSButtonHover8.setText("X");
        rSButtonHover8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        rSButtonHover8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover8ActionPerformed(evt);
            }
        });

        rSButtonHover9.setBackground(new java.awt.Color(153, 51, 0));
        rSButtonHover9.setText("Signout");
        rSButtonHover9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        rSButtonHover9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover9ActionPerformed(evt);
            }
        });

        rSButtonHover10.setBackground(new java.awt.Color(153, 51, 0));
        rSButtonHover10.setText("HOME");
        rSButtonHover10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        rSButtonHover10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover10ActionPerformed(evt);
            }
        });

        rSButtonHover11.setBackground(new java.awt.Color(153, 51, 0));
        rSButtonHover11.setText("Saving");
        rSButtonHover11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        rSButtonHover11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover11ActionPerformed(evt);
            }
        });

        rSButtonHover12.setBackground(new java.awt.Color(51, 0, 153));
        rSButtonHover12.setText("MONEY MANAGER");
        rSButtonHover12.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        rSButtonHover12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover12ActionPerformed(evt);
            }
        });

        rSButtonHover13.setBackground(new java.awt.Color(102, 0, 102));
        rSButtonHover13.setText("Setting");
        rSButtonHover13.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        rSButtonHover13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover13ActionPerformed(evt);
            }
        });

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/money/manager/images/money.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton10)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rSButtonHover10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rSButtonHover4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rSButtonHover7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rSButtonHover5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rSButtonHover6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rSButtonHover11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(rSButtonHover13, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rSButtonHover9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addComponent(rSButtonHover12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rSButtonHover8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rSButtonHover12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rSButtonHover8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSButtonHover5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonHover6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonHover9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonHover10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonHover7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonHover4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonHover11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonHover13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        Body.setBackground(new java.awt.Color(204, 204, 204));
        Body.setLayout(new java.awt.BorderLayout());

        Profile.setBackground(new java.awt.Color(0, 0, 0));
        Profile.setPreferredSize(new java.awt.Dimension(350, 450));
        Profile.setLayout(new java.awt.BorderLayout());

        Picture.setBackground(new java.awt.Color(0, 102, 102));
        Picture.setPreferredSize(new java.awt.Dimension(400, 200));
        Picture.setLayout(new java.awt.GridLayout(1, 1));

        Mahdi_Pic.setBackground(new java.awt.Color(0, 0, 0));
        Mahdi_Pic.setForeground(new java.awt.Color(255, 255, 255));
        Mahdi_Pic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mahdi_Pic.setIcon(new javax.swing.ImageIcon("E:\\OneDrive - Military Institute of Science and Technology (MIST)\\Level-2 Term-2\\CSE-220 OOP Sessional-II\\javaproject\\src\\money\\manager\\images\\202014028.JPG")); // NOI18N
        Mahdi_Pic.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        Mahdi_Pic.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Mahdi_Pic.setFocusable(false);
        Mahdi_Pic.setPreferredSize(new java.awt.Dimension(150, 150));
        Mahdi_Pic.setRequestFocusEnabled(false);
        Picture.add(Mahdi_Pic);

        Profile.add(Picture, java.awt.BorderLayout.CENTER);

        User_Info.setBackground(new java.awt.Color(153, 153, 153));
        User_Info.setPreferredSize(new java.awt.Dimension(400, 250));
        User_Info.setLayout(new java.awt.BorderLayout());

        Welcome.setAlignment(java.awt.Label.CENTER);
        Welcome.setBackground(new java.awt.Color(0, 153, 102));
        Welcome.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Welcome.setMinimumSize(new java.awt.Dimension(214, 27));
        Welcome.setPreferredSize(new java.awt.Dimension(214, 45));
        Welcome.setText("Welcome, Mahdi Mohtasim");
        User_Info.add(Welcome, java.awt.BorderLayout.CENTER);

        Info.setBackground(new java.awt.Color(204, 204, 204));
        Info.setPreferredSize(new java.awt.Dimension(400, 205));
        Info.setLayout(new java.awt.GridLayout(5, 2));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Email :");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel1.setPreferredSize(new java.awt.Dimension(60, 15));
        Info.add(jLabel1);

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("mahdimohtasim@gmail.com");
        Info.add(jLabel6);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Phone :");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel2.setPreferredSize(new java.awt.Dimension(60, 15));
        Info.add(jLabel2);

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("01740997497");
        Info.add(jLabel7);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Gender :");
        jLabel3.setToolTipText("");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel3.setPreferredSize(new java.awt.Dimension(60, 15));
        Info.add(jLabel3);

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Male");
        Info.add(jLabel8);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Occupation :");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel4.setPreferredSize(new java.awt.Dimension(60, 15));
        Info.add(jLabel4);

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Student");
        Info.add(jLabel5);

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Status :");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel9.setPreferredSize(new java.awt.Dimension(60, 15));
        Info.add(jLabel9);

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Under Budget");
        Info.add(jLabel10);

        User_Info.add(Info, java.awt.BorderLayout.SOUTH);

        Profile.add(User_Info, java.awt.BorderLayout.SOUTH);

        Body.add(Profile, java.awt.BorderLayout.WEST);

        User_Settings.setBackground(new java.awt.Color(102, 102, 102));
        User_Settings.setPreferredSize(new java.awt.Dimension(434, 450));
        User_Settings.setLayout(new java.awt.BorderLayout());

        panel2.setBackground(new java.awt.Color(51, 51, 51));
        panel2.setPreferredSize(new java.awt.Dimension(392, 100));
        panel2.setLayout(new javax.swing.BoxLayout(panel2, javax.swing.BoxLayout.LINE_AXIS));

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        label2.setForeground(new java.awt.Color(204, 204, 204));
        label2.setText("Change Your Settings Here");
        panel2.add(label2);

        User_Settings.add(panel2, java.awt.BorderLayout.NORTH);

        panel1.setBackground(new java.awt.Color(102, 102, 102));

        panel4.setBackground(new java.awt.Color(102, 102, 102));
        panel4.setPreferredSize(new java.awt.Dimension(120, 120));
        panel4.setLayout(new java.awt.GridLayout(5, 1));

        label3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label3.setText("Username");
        panel4.add(label3);

        label4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label4.setText("Password");
        panel4.add(label4);

        label7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label7.setText("Rewrite Password");
        panel4.add(label7);

        label5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label5.setText("Select Currency");
        panel4.add(label5);

        label6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label6.setText("Credit Card");
        panel4.add(label6);

        panel6.setBackground(new java.awt.Color(102, 102, 102));
        panel6.setForeground(new java.awt.Color(102, 102, 102));
        panel6.setLayout(new java.awt.GridLayout(5, 1));

        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setAutoscrolls(false);
        jTextField1.setVerifyInputWhenFocusTarget(false);
        panel6.add(jTextField1);

        jPasswordField1.setForeground(new java.awt.Color(0, 0, 0));
        panel6.add(jPasswordField1);

        jPasswordField2.setForeground(new java.awt.Color(0, 0, 0));
        panel6.add(jPasswordField2);

        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Taka", "Dollars" }));
        panel6.add(jComboBox1);

        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        panel6.add(jTextField2);

        jButton9.setBackground(new java.awt.Color(204, 204, 204));
        jButton9.setForeground(new java.awt.Color(0, 0, 0));
        jButton9.setText("Save");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jButton9))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(panel6, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel4, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(panel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        User_Settings.add(panel1, java.awt.BorderLayout.CENTER);

        Body.add(User_Settings, java.awt.BorderLayout.CENTER);

        getContentPane().add(Body, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonHover4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonHover4ActionPerformed

    private void rSButtonHover5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonHover5ActionPerformed

    private void rSButtonHover6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonHover6ActionPerformed

    private void rSButtonHover7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonHover7ActionPerformed

    private void rSButtonHover8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover8ActionPerformed

        // TODO add your handling code here:
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonHover8ActionPerformed

    private void rSButtonHover9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonHover9ActionPerformed

    private void rSButtonHover10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonHover10ActionPerformed

    private void rSButtonHover11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonHover11ActionPerformed

    private void rSButtonHover12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonHover12ActionPerformed

    private void rSButtonHover13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonHover13ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel Body;
    private java.awt.Panel Info;
    private javax.swing.JLabel Mahdi_Pic;
    private java.awt.Panel Picture;
    private java.awt.Panel Profile;
    private java.awt.Panel User_Info;
    private java.awt.Panel User_Settings;
    private java.awt.Label Welcome;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel4;
    private java.awt.Panel panel6;
    private rojerusan.RSButtonHover rSButtonHover10;
    private rojerusan.RSButtonHover rSButtonHover11;
    private rojerusan.RSButtonHover rSButtonHover12;
    private rojerusan.RSButtonHover rSButtonHover13;
    private rojerusan.RSButtonHover rSButtonHover4;
    private rojerusan.RSButtonHover rSButtonHover5;
    private rojerusan.RSButtonHover rSButtonHover6;
    private rojerusan.RSButtonHover rSButtonHover7;
    private rojerusan.RSButtonHover rSButtonHover8;
    private rojerusan.RSButtonHover rSButtonHover9;
    // End of variables declaration//GEN-END:variables
}
