/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package money.manager;

import java.awt.*;

/**
 *
 * @author MdMahdiMohtasim
 */
public class Settings extends javax.swing.JFrame {

    /**
     * Creates new form Settings
     */
    public Settings() {
        initComponents();
    }
    
    Toolkit tk = Toolkit.getDefaultToolkit();
    int screenWidth = (int)tk.getScreenSize().getWidth();
    int screenHeight = (int)tk.getScreenSize().getHeight();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new java.awt.Panel();
        jButton1 = new javax.swing.JButton();
        label1 = new java.awt.Label();
        Menu = new java.awt.Panel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        Body = new java.awt.Panel();
        Profile = new java.awt.Panel();
        Picture = new java.awt.Panel();
        Mahdi_Pic = new javax.swing.JLabel();
        User_Info = new java.awt.Panel();
        Welcome = new java.awt.Label();
        Info = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        User_Settings = new java.awt.Panel();
        panel2 = new java.awt.Panel();
        label2 = new java.awt.Label();
        panel1 = new java.awt.Panel();
        panel4 = new java.awt.Panel();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label7 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        panel6 = new java.awt.Panel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Settings");
        setBounds((screenWidth/2)-400, (screenHeight/2)-250, 0, 0);
        setUndecorated(true);

        Header.setBackground(new java.awt.Color(51, 153, 255));
        Header.setPreferredSize(new java.awt.Dimension(800, 50));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/x.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.setRequestFocusEnabled(false);
        jButton1.setRolloverEnabled(false);
        jButton1.setVerifyInputWhenFocusTarget(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Header.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, -1, -1));

        label1.setFont(new java.awt.Font("Dialog", 1, 27)); // NOI18N
        label1.setText("Settings");
        Header.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 3, -1, -1));

        Menu.setBackground(new java.awt.Color(51, 153, 255));
        Menu.setLayout(new java.awt.GridLayout(1, 7, 2, 0));

        jButton2.setBackground(new java.awt.Color(51, 153, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Home");
        jButton2.setAlignmentY(0.6F);
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setDefaultCapable(false);
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.setRequestFocusEnabled(false);
        jButton2.setRolloverEnabled(false);
        jButton2.setVerifyInputWhenFocusTarget(false);
        Menu.add(jButton2);

        jButton3.setBackground(new java.awt.Color(51, 153, 255));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Monthly");
        jButton3.setAlignmentY(0.6F);
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);
        jButton3.setRequestFocusEnabled(false);
        jButton3.setRolloverEnabled(false);
        jButton3.setVerifyInputWhenFocusTarget(false);
        Menu.add(jButton3);

        jButton4.setBackground(new java.awt.Color(51, 153, 255));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Daily");
        jButton4.setAlignmentY(0.6F);
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusPainted(false);
        jButton4.setFocusable(false);
        jButton4.setRequestFocusEnabled(false);
        jButton4.setRolloverEnabled(false);
        jButton4.setVerifyInputWhenFocusTarget(false);
        Menu.add(jButton4);

        jButton5.setBackground(new java.awt.Color(51, 153, 255));
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Filter");
        jButton5.setAlignmentY(0.6F);
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusPainted(false);
        jButton5.setFocusable(false);
        jButton5.setRequestFocusEnabled(false);
        jButton5.setRolloverEnabled(false);
        jButton5.setVerifyInputWhenFocusTarget(false);
        Menu.add(jButton5);

        jButton6.setBackground(new java.awt.Color(51, 153, 255));
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("Stats");
        jButton6.setAlignmentY(0.6F);
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setFocusPainted(false);
        jButton6.setFocusable(false);
        jButton6.setRequestFocusEnabled(false);
        jButton6.setRolloverEnabled(false);
        jButton6.setVerifyInputWhenFocusTarget(false);
        Menu.add(jButton6);

        jButton7.setBackground(new java.awt.Color(51, 153, 255));
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setText("Savings");
        jButton7.setAlignmentY(0.6F);
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setFocusPainted(false);
        jButton7.setFocusable(false);
        jButton7.setRequestFocusEnabled(false);
        jButton7.setRolloverEnabled(false);
        jButton7.setVerifyInputWhenFocusTarget(false);
        Menu.add(jButton7);

        jButton8.setBackground(new java.awt.Color(51, 153, 255));
        jButton8.setForeground(new java.awt.Color(0, 0, 0));
        jButton8.setText("Settings");
        jButton8.setAlignmentY(0.6F);
        jButton8.setBorder(null);
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setFocusPainted(false);
        jButton8.setFocusable(false);
        jButton8.setRequestFocusEnabled(false);
        jButton8.setRolloverEnabled(false);
        jButton8.setVerifyInputWhenFocusTarget(false);
        Menu.add(jButton8);

        Header.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 2, 420, 40));

        getContentPane().add(Header, java.awt.BorderLayout.NORTH);

        Body.setBackground(new java.awt.Color(204, 204, 204));
        Body.setLayout(new java.awt.BorderLayout());

        Profile.setBackground(new java.awt.Color(0, 0, 0));
        Profile.setPreferredSize(new java.awt.Dimension(400, 450));
        Profile.setLayout(new java.awt.BorderLayout());

        Picture.setBackground(new java.awt.Color(0, 102, 102));
        Picture.setPreferredSize(new java.awt.Dimension(400, 200));
        Picture.setLayout(new java.awt.GridLayout(1, 1));

        Mahdi_Pic.setBackground(new java.awt.Color(0, 0, 0));
        Mahdi_Pic.setForeground(new java.awt.Color(255, 255, 255));
        Mahdi_Pic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mahdi_Pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/202014028.JPG"))); // NOI18N
        Mahdi_Pic.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        Mahdi_Pic.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Mahdi_Pic.setFocusable(false);
        Mahdi_Pic.setPreferredSize(new java.awt.Dimension(150, 150));
        Mahdi_Pic.setRequestFocusEnabled(false);
        Picture.add(Mahdi_Pic);

        Profile.add(Picture, java.awt.BorderLayout.PAGE_START);

        User_Info.setBackground(new java.awt.Color(153, 153, 153));
        User_Info.setPreferredSize(new java.awt.Dimension(400, 250));
        User_Info.setLayout(new java.awt.BorderLayout());

        Welcome.setAlignment(java.awt.Label.CENTER);
        Welcome.setBackground(new java.awt.Color(0, 153, 102));
        Welcome.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Welcome.setMinimumSize(new java.awt.Dimension(214, 27));
        Welcome.setPreferredSize(new java.awt.Dimension(214, 45));
        Welcome.setText("Welcome, Mahdi Mohtasim");
        User_Info.add(Welcome, java.awt.BorderLayout.PAGE_START);

        Info.setBackground(new java.awt.Color(204, 204, 204));
        Info.setPreferredSize(new java.awt.Dimension(400, 205));
        Info.setLayout(new java.awt.GridLayout(5, 2));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Email :");
        Info.add(jLabel1);

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("mahdimohtasim@gmail.com");
        Info.add(jLabel6);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Phone :");
        Info.add(jLabel2);

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("01740997497");
        Info.add(jLabel7);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Gender :");
        jLabel3.setToolTipText("");
        Info.add(jLabel3);

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Male");
        Info.add(jLabel8);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Occupation :");
        Info.add(jLabel4);

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Student");
        Info.add(jLabel5);

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Status :");
        Info.add(jLabel9);

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Under Budget");
        Info.add(jLabel10);

        User_Info.add(Info, java.awt.BorderLayout.LINE_END);

        Profile.add(User_Info, java.awt.BorderLayout.SOUTH);

        Body.add(Profile, java.awt.BorderLayout.WEST);

        User_Settings.setBackground(new java.awt.Color(102, 102, 102));
        User_Settings.setLayout(new java.awt.BorderLayout());

        panel2.setBackground(new java.awt.Color(51, 51, 51));
        panel2.setPreferredSize(new java.awt.Dimension(392, 100));
        panel2.setLayout(new javax.swing.BoxLayout(panel2, javax.swing.BoxLayout.LINE_AXIS));

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        label2.setForeground(new java.awt.Color(204, 204, 204));
        label2.setText("Change Your Settings Here");
        panel2.add(label2);

        User_Settings.add(panel2, java.awt.BorderLayout.NORTH);

        panel1.setBackground(new java.awt.Color(102, 102, 102));

        panel4.setBackground(new java.awt.Color(102, 102, 102));
        panel4.setPreferredSize(new java.awt.Dimension(120, 120));
        panel4.setLayout(new java.awt.GridLayout(5, 1));

        label3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label3.setText("Username");
        panel4.add(label3);

        label4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label4.setText("Password");
        panel4.add(label4);

        label7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label7.setText("Rewrite Password");
        panel4.add(label7);

        label5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label5.setText("Select Currency");
        panel4.add(label5);

        label6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label6.setText("Credit Card");
        panel4.add(label6);

        panel6.setBackground(new java.awt.Color(102, 102, 102));
        panel6.setForeground(new java.awt.Color(102, 102, 102));
        panel6.setLayout(new java.awt.GridLayout(5, 1));

        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setAutoscrolls(false);
        jTextField1.setVerifyInputWhenFocusTarget(false);
        panel6.add(jTextField1);

        jPasswordField1.setForeground(new java.awt.Color(0, 0, 0));
        panel6.add(jPasswordField1);

        jPasswordField2.setForeground(new java.awt.Color(0, 0, 0));
        panel6.add(jPasswordField2);

        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Taka", "Dollars" }));
        panel6.add(jComboBox1);

        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        panel6.add(jTextField2);

        jButton9.setBackground(new java.awt.Color(204, 204, 204));
        jButton9.setForeground(new java.awt.Color(0, 0, 0));
        jButton9.setText("Save");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton9)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel6, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel6, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jButton9)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        User_Settings.add(panel1, java.awt.BorderLayout.SOUTH);

        Body.add(User_Settings, java.awt.BorderLayout.CENTER);

        getContentPane().add(Body, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel Body;
    private java.awt.Panel Header;
    private java.awt.Panel Info;
    private javax.swing.JLabel Mahdi_Pic;
    private java.awt.Panel Menu;
    private java.awt.Panel Picture;
    private java.awt.Panel Profile;
    private java.awt.Panel User_Info;
    private java.awt.Panel User_Settings;
    private java.awt.Label Welcome;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel4;
    private java.awt.Panel panel6;
    // End of variables declaration//GEN-END:variables
}
